### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: net/minecraft/world/entity/item/ItemEntity

### ISSUE THREAD

**Issue by ofunny** [snowgears/shopbugs#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 
- Shop Version:
```

### Server startup log

https://pastebin.com/iMBZJgsz

### Shop config files

On request only

### Error log (if applicable)

https://pastebin.com/E2WSxsHi

### Bug description

Exception on startup after updating Paper to 1.20.2 and updating Shop to 1.8.4.6 – https://pastebin.com/E2WSxsHi
Plugin is disabling and unusable.

### Steps to reproduce

Install Paper [git-Paper-318 (MC: 1.20.2)]
Install Shop to 1.8.4.6
Startup the server

### Expected behaviour

No exception, working plugin

### Actual behaviour

Exception, no working plugin

**Comment by snowgears** [comment]
Please use 1.8.4.5 for 1.20.2. 1.8.4.6 is for 1.20.4 only. I will fix this!
